language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'

script:
  - phpunit -v -c phpunit.xml

branches:
    only:
      - master

before_script:
  - phpenv config-rm xdebug.ini
  - chmod -R 744 /home/travis/build/mmamedov/page-cache/tests/tmp
  - composer install -o