language: php
php:
  - '5.5'
  - '5.6'

script:
  - phpunit -v --bootstrap tests/bootstrap.php -c phpunit.xml

branches:
    only:
      - master

before_script:
  - phpenv config-rm xdebug.ini
  - composer install -o